#+title:      how i came to use emacs and other things
#+date:       [2023-06-29 Thu 18:01]
#+filetags:   :emacs:explanation:linux:origin:raspberrypi:story:terminal:
#+identifier: 20230629T180135

* This is the story of how I came to use Emacs and other things
I'm tired of repeating myself so I'm writing this down so I don't have to. You're probably only here if you asked me how I came to learn about Emacs and the CLI and other things. Well, this is the story:

It begins with a Pandemic. /The/ Pandemic. Yes, that one.

I know it's a long time ago now for most people, but that's where it starts. It feels like a lifetime ago for me. I was a first year overseas person working for a company to manage things, However, halfway through my time there, the Pandemic hit.

Paris was locked down. Everything was closed. And I mean /everything/. It wasn't like in the states - we had to have permission slips to go outside for an hour max a day (there were exceptions but most people stuck to the rules). Cafes, restaurants, stores - everything was closed. Of course, it being France, they opened the tobacco shops back up first but everything else remained closed. (Crazy, inorite?)

At that point, my Western Digital "Network Drive" died. It was non-responsive. I had a lot of stuff on there so I was pretty mad about that. Note: I'll never trust "Network Drives" again. 😛

So, I needed to fix it. But I didn't know how. I couldn't get it fixed at a shop because no shops were open. Also, I was paid a pretty small salary at the time so I couldn't really afford to spend hundreds of euros getting it fixed or recovered.

A friend of mine who works in tech told me to buy a Raspberry Pi because Linux could fix my drive or recover my info. I had heard of these things, but barely and very vaguely. But anyway, I followed her directions and I bought one online. It was delivered to me in a few days (I guess they had nothing better to do and deliveries were up all over the place).

So there I was, sitting on the floor of my living room, the Raspberry Pi hooked up to my TV. Anyway, it took me about a week to look stuff up on my MacBook Pro and figure out how to recover my stuff. /Believe me/ it was hard. I had to learn about 'df' and 'du' and 'fdisk' and sectors and partitions - all stuff I had never, ever, heard about before. The only things I had were my computers and online sites that talked about this stuff in, honestly, really cryptic ways.

Anyway, I eventually got it to work after a week of pulling my hair out, sitting cross-legged on the floor. But it worked and I recovered 100% of my drive. *100%!* It was at like 2 or 3am (I honestly can't remember) and I ran around my apartment laughing and shouting with joy.

My neighbours politely never remarked on this or complained.

So then what happened? Well, I had this new thing in my life: My Raspberry Pi. I figured...maybe I can use it for stuff. I also figured that this would *never* happen to me again. So I learned about how to make an NAS system with my Pi, and I bought some drives to do that. I watched a lot of videos on Linux and the Raspberry Pi on how to set up an NAS. And I learned about much more involving Linux and that led me to Emacs (even before Vim). See, I was using Nano before and I didn't know what else there was. But I came across a video demonstrating Org Mode and I was blown away. The video was [[https://www.youtube.com/watch?v=SzA2YODtgK4][ Getting Started With Org Mode]] by [[https://harryrschwartz.com][Harry Schwartz]]. I mean it really, /really/ blew me away. I don't know why because his screen is so ugly, but the things you could do with text - I had never seen that before. Ever. Also, he just sounds like such a nice person in the presentation. Anyway, I was totally hooked.

So I installed Emacs on my MacBook which was still working fine of course. And then I learned about other things.

First, I started learning about [[https://www.spacemacs.org][Spacemacs]] because I saw some posts on Reddit how it was easier for newbies. Then, I switched to [[https://github.com/doomemacs/doomemacs][Doom Emacs]], because I heard it was faster. But then, after a very short time (and getting tired of Doom breaking every update), I went all vanilla. The videos which helped me the most in doing that (and also learning Org-Mode) were:

- [[https://www.youtube.com/@mzamansky][Mike Zamansky]] for setting up Emacs from scratch with an org-mode config.org file. Also great quick video reviews of different packages.
- [[https://www.youtube.com/@koenighaunstetten][Rainer König]] for learning all things org-mode. He's amazing, and he sounds like Arnold Schwarzenegger. (He is aware of this)
- [[https://www.youtube.com/@SystemCrafters][System Crafters]] for learning extra deep stuff in Emacs and much longer videos explaining them (such as setting up mu4e in depth and other things). Also, he's got a great community on [[https://matrix.org][Matrix]] and you can find his web page at [[https://systemcrafters.net][System Crafters]].

Also, in one of the communities online, I met a guy named [[https://universeodon.com/@remi][Remi]] and he helped me with some CLI (Command Line Interface) stuff as well as Emacs in many ways.

Eventually that led me to my new job (which is not tech at all) because of a personal interaction I had with somebody thanks to learning about Linux/online communities. This was totally random but it wouldn't have happened without me getting involved in online communities. My job has nothing to do with tech really, but I wouldn't have met my new boss without going to find something out at the right place and right time. Also, I use Emacs in my job every day to organise things and I can't live without it.

I have taken my MacBook Pro to bed with me a couple of times just to feel Emacs close to me.

So that's how I learned about Emacs and a little bit of CLI and Linux at first.

I hope you enjoyed reading it.

Summer.
