#+title:      emacs sentences reddit post
#+date:       [2023-07-02 Sun 22:47]
#+filetags:   :configuration:defaults:emacs:post:reddit:sentences:
#+identifier: 20230702T224750

Ok I'm sorry if this comes across as a bit of a rant, but maybe it'll get to the Emacs higher-ups. I hope so:

This week, I ran a poll on my Mastodon to see who uses Vanilla Keybindings vs Modal. As a Meow user since a year, I was curious. Given the results (hugely in favor of Vanilla), I decided to go back to trying Vanilla. And I'm really loving it. I feel like I'm actually faster in a way. It's hard to describe, but I prefer it over modal. Then again, I'm not a coder so I think maybe the reason that coders like modal is maybe it fits their typing/editing patterns better? I'm not sure.

Anyway, as I said: I love Emacs and Vanilla keybindings. Except, as we all know, Emacs can be a bit of a relic. And sometimes, it's like the people in charge refuse to even acknowledge that the world has changed. That's fine - I get why, and I still love Emacs. But here's an example of it being bad:

So I changed to Vanilla a few days ago, and I'm actually doing the tutorial again. You know why? Because that's what Emacs recommends for you to learn stuff. I wanted to practice the keybindings again a bit, so I did. Three times, in fact.

And here's the thing: I'm loving the vanilla keybindings but some of them didn't work with my own text. Can you guess which ones?

The ones involving selection/moving;editing/deleting sentences. They would manipulate the entire paragraph. Everything else works, but not those.

Why?

Well, in case you didn't know it, back in the dark ages of civilization, probably around the discovery of fire, people used to type two spaces after a period to denote a new sentence. Well, hey, I only know about this because I recently read an article explaining it about a month or two ago. But what I wasn't aware of is that Emacs is looking for those two spaces. You know - the two spaces that very few people actually use in their writing these days (the modern era).

Turns out that there's a variable you can set: sentence-end-double-space to t or nil. If it's nil, then you're a normal modern person who doesn't remember the Gutenberg press. But Emacs defaults it to t, meaning that all those wonderful editing commands for entire sentences won't work for you. (At least they didn't for me until I changed that variable).

Ok, here's the deal: why does this upset me? Why should this be changed?

I'll tell you why: I'm not a coder but I'm not an Emacs newbie either. I know how to use C-h v, for instance. I've been using Emacs for a couple of years now. I wrote my own config. If a newbie comes across that tutorial (which Emacs encourages), it's not gonna mention that (as far as I can recall - please tell me if I've missed something obvious). It's not gonna make sense why all the sentence commands don't work as expected but everything else does.

My advice: put a nice explanatory paragraph in the tutorial, or set the default of that variable to nil. One or the other. Don't expect people to come to Emacs thinking that we're still in the typewriter age when gas lanterns were a thing and all the news was about how Archduke Ferdinand was just assassinated. Most of us don't use double spaces. It's not a thing anymore. We also don't use white-out (I read about that too).

Change it or explain it so it's clear.

Thanks, and sorry for the rant. I obvs love Emacs, I use it all day, it's fantastic, I just wish sometimes that it wasn't stuck in 1976. 😛

/rant off

P.S. I still love the vanilla keybindings more and more. You might think this is nit-picking but maybe it's just my OCD kicking off. I like Emacs to be as perfect as can be because it's such an amazing tool.

https://www.reddit.com/r/emacs/comments/14oxhkv/sentences/
