#+title:      how to read the wheel of time books
#+date:       [2023-05-22 Mon 08:25]
#+filetags:   :books:fantasy:list:
#+identifier: 20230522T082537

https://www.themarysue.com/heres-how-to-read-the-wheel-of-time-books-in-order/

* [[https://www.themarysue.com/heres-how-to-read-the-wheel-of-time-books-in-order/][Here's How To Read 'The Wheel of Time' Books in Order | The Mary Sue]] :website:

[2023-05-22 Mon 08:26]

** Here's How To Read ‘The Wheel of Time' Books in Order

By [[https://www.themarysue.com/author/siobhan-ball/][Siobhan Ball]] May 20th, 2023, 6:25 pm

Robert Jordan's (and for the last three installments, Brandon Sanderson's) /The Wheel of Time/ series is a must-read for every classic fantasy fan. But there's just so. Many. Books. It can be really hard to figure out where you're supposed to start. And the repetition of themes and storylines in the series makes it even more confusing to find your place in the series. I've definitely found myself asking “Wait, have I read this book before?”, when actually I hadn't. So to help you out, The Mary Sue has created a guide to reading every book in /The Wheel of Time/ series in order, that will help you keep track of which book you're actually on.

**** /New Spring/
Though written much later than most of the books, /New Spring/ is actually a prequel, co-written by Jordan and Sanderson. Set twenty years before /The Eye of the World, New Spring/ follows Moiraine Damodred and Siuan Sanche in their early days as Aes Sedai, right at the end of the Aiel War. We find out how they first learned of the prophecies of the rebirth of the Dragon, and began researching and preparing for it. If you want to read the series in order of publication rather than events, then skip this one until you've read the rest of the series first. But if you want to read chronologically, start here.

**** /The Eye of the World/
/The Eye of the World/ is the official first published book in the series. After a prologue setting up important lore for the series, /The Eye of the World/ introduces several of the protagonists, including the unaware reborn legendary hero Rand al'Thor. After their peaceful home town of Emond's Field is attacked by Trollocs, the teenaged heroes flee, accompanied by an Aes Sedhai and her warder as well as some other protectors. The teens are separated from each other on their journey, developing new abilities and connections, before reuniting to travel to the Eye of the World -- an untainted reserve of Saidin (the masculine side of the One Essence, most of which was corrupted at the end of the age of legends) that contains one of the seven seals that keep the Dark One imprisoned.

**** /The Great Hunt/
This is the book where Rand is identified as the Dragon Reborn, though he continues to struggle with accepting his powers. In /The Great Hunt/, they travel to a parallel world and pursue the stolen Horn of Valere. Several of their friends face capture in the process, before Rand faces the villain Ba'alzamon once again for a climactic battle.

**** /The Dragon Reborn/
After Moraine declares Rand's status as the eponymous Dragon Reborn, he goes to prove himself in Tear while pursued by friends and foes alike. Rand makes new allies along the way, and even those companions initially headed elsewhere find their roads leading to Tear as well. /The Dragon Reborn/ ends in a battle for the fortress known as the Stone of Tear (and another show down with Ba'alzamon).

**** /The Shadow Rising/
Our heroes are split into four groups in /The Shadow Rising/. Rand travels to the Aiel wastes, where he wins them over as their chief of chiefs. His childhood friend Perrin returns home to rally the villages of their homeland against the Trolloc armies, becoming their unified leader in the process. Egwene and Aviendha travel to the Aiel Wastes so Egwene can learn to travel the Dreamworld. Princess Elayne and Nynaeve go in search of the Black Ajah, and a coupe is underway at the White Tower.

**** /The Fires of Heaven/
In /The Fires of Heaven/, a schism among the Aiel sees the four clans who won't accept an outsider's leadership leaving to attack the city of Carhien, with Rand and the other seven clans in hot pursuit. Meanwhile, Queen Morgase of Andor, Elayne's mother, is deposed (and presumed dead) by one of the Forsaken.

**** /Lord of Chaos/
/Lord of Chaos/ finds Rand bonded against his will as an Aes Sedai's warder, and then later captured and tortured by Aes Sedai loyal to the White Tower's new regime. Thanks to the number of seals already broken, the Dark One is able to exert more power in the world and initiates a period of global warming, among other acts of malfeasance. Meanwhile, Princess Elayne and Nynaeve learn to heal those whose bonds with the one power have been severed, before embarking on a quest to find the Bowl of Winds to take back control of the climate. Perrin leads an army to free Rand and bring the rebel Aes Sedai back under control. This is also the book where Rand establishes the Black Tower for male channelers, allowing them to train despite the risk of taint instead of “gentling” their powers away.

**** /A Crown of Swords/
Another book where the party splits (this time into three), /A Crown of Swords/ has Rand trying to quell the dissent on Carhien before doing battle with the Forsaken Sammael to wrest control of Illian and its Crown of Swords back from the dark. His childhood friend Egwene, now leader of the rebel Aes Sedai, plays politics with the warring factions to try and regain control of the White Tower, while Elayne and Nynaeve continue their quest for the Bowl of Winds.

**** /The Path of Daggers/
/The Path of Daggers/ begins with a victory: Elayne, Nynaeve, and their channeler allies find and use the Bowl to restore the climate. Yay! But the effects of that win later backfire, interfering with Rand's use of the One Power during a seminal battle with the Seanchan. Meanwhile, Egwene leads her Aes Sedai to besiege the White Tower.

**** /Winter's Heart/
/Winter's Heart/ sees our heroes once again divided, as Perrin races off to rescue his kidnapped wife, Elayne tries to stabilize her kingdom, and Mat (making his return to the story) kidnaps Tuon, the heir to the Seanchan empire while escaping one of the cities under its occupation. Rand is bonded as a warder to the three women he's in love with as a form of marriage, and goes on to cleanse Saidin of its taint -- protecting male channelers from madness.

**** /Crossroads of Twilight/
Perrin continues tracking his wife's kidnappers, becoming increasingly unprincipled in his efforts to find her, while Mat attempts to romance Tuon. All roads lead to the Seanchan, as they offer Perrin an alliance and agree to treat with Rand as long as he agrees to a meeting with their crown princess. Though Egwene's siege is going well, she ends up kidnapped by agents of the White Tower, finding herself a prisoner on the inside.

**** /Knife of Dreams/
In /Knife of Dreams,/ the princess Rand has been sent to meet with turns out to be one of the Forsaken in disguise, and it costs him dearly. The real Tuon, after learning that the Forsaken have murdered her mother and sent an armed force to kill her too, enters into an alleged marriage of convenience with Mat before returning home to take control of her empire and drive the Forsaken out. Meanwhile, Perrin defeats the Shaido Aiel while rescuing his wife, and the politics surrounding the White and Black Towers becomes more complex.

**** /The Gathering Storm/
A traumatic event near the beginning of /The Gathering Storm/ sees Rand cut himself off from all emotions except rage, and comes very close to destroying the world himself as a result. Meanwhile, Tuon takes control of her empire, rejecting a truce with Rand because of the darkness she sees in him, and the rebel Aes Sedai launch their final attack on the White Tower.

Robert Jordan died before completing this book, so Brandon Sanderson took over and finished it. Sanderson went on to write the final three books (including the prequel) in the series.

**** /Towers of Midnight/
Reinvigorated by the revelations that drew him back from destroying the world, /Towers of Midnight has/ Rand start off on a heroic tear, fighting shadow spawn, righting wrongs, and raising up the down trodden. Deciding that the only way to defeat the Dark One is to destroy all the seals keeping him imprisoned, he brings this idea to Egwene. Now ruler of the White Tower, Egwene believes he's gone mad. She begins a plan to unify all nations against him, believing it will take all their resources combined to stop the Dragon from ending them all. Making things worse, the Black Tower has been taken over by the Forsaken, with those unwilling to swear to the Dark One unable to escape.

**** /A Memory of Light/
The final novel, /A Memory of Light/ brings things to a close, with Egwene and the armies of the world joining the siege, a combination of promises and prophecy to destroy the seals, and fight the Dark One by Rand's side.
